modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/juliand665/Dynamic-FPS/issues"

[[mods]]
modId = "dynamic_fps"
namespace = "net.lostluma"
version = "${version}"
displayName = "Dynamic FPS"
authors = "juliand665 & LostLuma"
description = "Reduce resource usage while Minecraft is in the background or idle."
logoFile = "assets/dynamic_fps/textures/icon.png"
displayTest = "IGNORE_ALL_VERSION"
credits = """
Thanks to:
  Authors:
    juliand665
    LostLuma

  Contributors:
    altrisi
    DenaryDev
    dima-dencep
    EuropaYou
    N4TH4NOT
    parly
    Pixaurora
    Setadokalo
    Siphalor
    sisby-folk
    triphora

  Illustrators:
    Pixaurora

  Translators:
    Alexander317
    AlphaKR93
    Altegar
    BurrConnie
    DecafDawren
    egeesin
    EuropaYou
    Felix14-v2
    FITFC
    godkyo98
    GuNanOvO
    Hubry
    ImVietnam
    ishi-sama
    kau19an
    kyrtion
    Lucanoria
    LotuxPunk
    Madis0
    mpustovoi
    N4TH4NOT
    notlin4
    Q2297045667
    Pixaurora
    raspberrygitq
    Rhbarber
    RinixGG
    Samekichi
    Shihyeon
    stijnvdkolk
    Taarek
    TheBossMagnus
    TheLegendofSaram
    wicivo
    XfedeX
    yichifauzi
"""
modUrl = "https://dapprgames.com/mods"
displayURL = "https://dapprgames.com/mods"
updateJSONURL = "https://api.lostluma.net/updates/dynamic-fps?platform=forge"

[[mixins]]
config = "dynamic_fps.mixins.json"

[[mixins]]
config = "dynamic_fps-common.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.dynamic_fps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4]"
ordering = "NONE"
side = "CLIENT"
